shifter/urls.py
from django.contrib import admin
from django.urls import include, path
import notifications.urls

urlpatterns = [
    path('planning/', include('shifts.urls.main')),
    path('', include('shifts.urls')),
    path('studies/', include('studies.urls')),
    path('ajax/', include('shifts.urls.ajax')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # new
    path('desiderata/', include('shifts.urls.desiderata')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

shifts/urls.py
from django.urls import include, path

from . import views

app_name = 'shifter'
handler404 = 'shifts.views.page_not_found'
urlpatterns = [
    path('', views.index, name='index'),
    path('today', views.todays, name='today'),
    path('user', views.user, name='user'),
    path('user/rev/<int:rid>', views.user, name='user'),
    path('user/<int:u>', views.user, name='user'),
    path('user/<int:u>/rev/<int:rid>', views.user, name='user'),

    path('team', views.team, name='team'),
    path('t', views.team_simple, name='team-simple'),  # FIXME add/id/remove?
    path('calendar.ics', views.icalendar_view, name='calendar'),
    path('ical', views.icalendar, name='calendar_public'),
    path('dates', views.dates, name='dates'),
    path('slots-update', views.dates_slots_update, name='slots-update-post'),
    path('phonebook', views.phonebook, name='phonebook'),
    path('phonebook-post', views.phonebook_post, name='phonebook-post'),
    path('ioc-update', views.ioc_update, name='ioc-update'),
    path('scheduled-work-time', views.scheduled_work_time, name='scheduled_work_time'),
    path('shifts', views.shifts, name='shifts'),
    path('shift-upload-csv', views.shifts_upload, name="shift-upload"),
    path('shift-upload-csv-post', views.shifts_upload_post, name="shift-upload-post"),
    path('shift-update', views.shifts_update, name="shift-update"),
    path('shift-update-post', views.shifts_update_post, name="shift-update-post"),
    path('assets', views.assets, name="assets"),
    path('assets-post', views.assets_post, name="assets-post"),
    path('assets-post-close', views.assets_post_close, name="assets-post-close"),
]

assets/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from members.models import Member
from django.urls import reverse

class AssetType(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)

    def __str__(self):
        return '{}'.format(self.name)


class Asset(models.Model):
    name = models.CharField(max_length=200)
    asset_type = models.ForeignKey(AssetType, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return '{} | {}'.format(self.asset_type.name, self.name)

    def search_display(self):
        return "Asset: " + str(self)

    def search_url(self):
        return reverse('assets')


class AssetBooking(models.Model):
    member = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL, related_name='using_member')
    booked_by = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL, related_name='booking_member')
    finished_by = models.ForeignKey(Member, null=True, blank=True, on_delete=models.SET_NULL, related_name='closing_member')

    asset = models.ForeignKey(Asset, blank=False, null=True, on_delete=models.SET_NULL)

    class BookingState(models.TextChoices):
        BOOKED = 'B', _('Booked')
        RETURNED = 'R', _('Returned')
        INUSE = 'U', _('In Use')

    state = models.CharField(max_length=1,
                             choices=BookingState.choices,
                             default=BookingState.BOOKED,)

    use_start = models.DateTimeField(blank=False)
    use_end = models.DateTimeField(blank=False)
    initial_comment = models.TextField(max_length=2000, blank=True, default=None, null=True)
    booking_created = models.DateTimeField(blank=False)
    booking_finished = models.DateTimeField(blank=True, null=True, )
    after_comment = models.TextField(max_length=2000, blank=True, default=None, null=True)

    def __str__(self):
        return '{} ({}) for {}'.format(self.member, self.asset, self.use_start)

    def asset_as_json(self, user=None):
        data = {'who': {'member': f'{self.member}', 'team': f'{self.member.team}'},
                'asset': {'type': f'{self.asset.asset_type.name}', 'name': f'{self.asset.name}'},
                'use_start': {'display': timezone.localtime(self.use_start).strftime('%b. %d, %Y, %I:%M%p'),
                              'order': self.use_start.timestamp()},
                'use_end': {'display': timezone.localtime(self.use_end).strftime('%b. %d, %Y, %I:%M%p'),
                            'order': self.use_end.timestamp()},
                'active': "Active" if self.state != AssetBooking.BookingState.RETURNED else "Over",
                'comment': f'<small> {timezone.localtime(self.booking_created).strftime("%b. %d, %Y, %I:%M%p")} / {self.booked_by}'
                           f'</small><br> {self.initial_comment}'}
        if self.state == 'R':
            data['closing'] = f"<span class='badge bg-success'>Booking over</span> <br>{self.booking_finished.strftime('%b. %d, %Y, %I:%M%p')}<br>{self.finished_by}<br>{self.after_comment}"
        else:
            if self.member != user and not user.is_staff:
                data['closing'] = '<span class="badge bg-warning">Booking ongoing</span>'
            else:
                data['closing'] = f"<a class='btn btn-outline-success' data-book_id={self.id} data-name='{self.asset.asset_type.name} - {self.asset.name}' onclick='test(event)'> End booking </a>"
        return data

    def search_display(self):
        return "Asset booking: " + str(self)

    def search_url(self):
        return reverse('assets')

assets/forms.py
from django import forms
from django.forms import ValidationError
from django.forms.widgets import HiddenInput
from .models import *

from assets.models import AssetBooking
from members.models import Member


class AssetBookingForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(AssetBookingForm, self).__init__(*args, **kwargs)
        if self.user.is_staff:
            self.fields['member'].choices = [(x.id, x.name) for x in Member.objects.all()]
        else:
            self.fields['member'].choices = [(x.id, x.name) for x in [self.user]]

    class Meta:
        model = AssetBooking
        fields = ('member', 'asset', 'use_start', 'use_end', 'initial_comment')


class AssetBookingFormClosing(forms.Form):
    booking_id = forms.CharField(widget=forms.HiddenInput(attrs={'id': 'closed_booking_id_to_set',}))
    after_comment = forms.CharField(widget=forms.Textarea)

shifts/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    username.widget.attrs = {'size': 8}
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)
    password.widget.attrs = {'size': 8}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

assets/views.py
from django.shortcuts import render

# Create your views here.

shifts/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render

from django.template.loader import render_to_string
from django.urls import reverse
import django.contrib.messages as messages
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_http_methods, require_safe
from django.db import IntegrityError

import members.models
from members.models import Team
from shifts.models import *
from assets.models import *
from studies.models import *
from assets.forms import AssetBookingForm, AssetBookingFormClosing
import datetime
import phonenumbers
from shifts.activeshift import prepare_active_crew, prepare_for_JSON
from shifts.contexts import prepare_default_context,prepare_user_context, prepare_team_context
from shifter.settings import DEFAULT_SHIFT_SLOT
from shifts.workinghours import find_daily_rest_time_violation, find_weekly_rest_time_violation


def page_not_found(request, exception):
    return render(request, "404.html", {})


@require_safe
def index(request):
    revisions = Revision.objects.filter(valid=True).order_by("-number")
    return prepare_main_page(request, revisions)


@require_http_methods(["POST"])
@csrf_protect
def index_post(request):
    revisions = Revision.objects.filter(valid=True).order_by("-number")
    revision = Revision.objects.filter(number=request.POST['revision']).first()
    filtered_campaigns = [int(i) for i in request.POST.getlist('campaign[]')]
    all_roles = request.POST.get('all_roles', None) is not None
    return prepare_main_page(request, revisions, revision=revision,
                             filtered_campaigns=filtered_campaigns, all_roles=all_roles)


def prepare_main_page(request, revisions, revision=None, filtered_campaigns=None, all_roles=False):
    if revision is None:
        revision = revisions.first()
    someDate = datetime.datetime.now() + datetime.timedelta(days=-61)  # default - always last two months
    scheduled_campaigns = Campaign.objects.filter(revision=revision).filter(date_end__gt=someDate)
    if filtered_campaigns is not None:
        scheduled_campaigns = Campaign.objects.filter(revision=revision).filter(id__in=filtered_campaigns)

    scheduled_shifts = Shift.objects.filter(revision=revision).filter(campaign__in=scheduled_campaigns)\
                            .filter(role=None)\
                            .order_by('date', 'slot__hour_start', 'member__role__priority')

    scheduled_studies = StudyRequest.objects.filter(state__in=["B","D"]).order_by('slot_start', 'priority')

    if all_roles:
        scheduled_shifts = Shift.objects.filter(revision=revision).filter(campaign__in=scheduled_campaigns)\
                                .order_by('date', 'slot__hour_start', 'member__role__priority')

    context = {
        'revisions': revisions,
        'displayed_revision': revision,
        'scheduled_shifts_list': scheduled_shifts,
        'scheduled_studies_list': scheduled_studies,
        'campaigns': Campaign.objects.filter(revision=revision),
        'scheduled_campaigns_list': scheduled_campaigns,
        'all_roles': all_roles
    }
    return render(request, 'index.html', prepare_default_context(request, context))


@require_safe
def dates(request):
    context = {
        'campaigns': Campaign.objects.all(),
        'slots': Slot.objects.all().order_by('hour_start'),
        'shiftroles': ShiftRole.objects.all(),
        'memberroles': members.models.Role.objects.all(),
        'assets': Asset.objects.all()
    }
    return render(request, 'dates.html', prepare_default_context(request, context))


@login_required
@require_http_methods(["POST"])
@csrf_protect
def dates_slots_update(request):
    count = 0
    for slot in Slot.objects.all():
        slot.op = False
        toUpdate = request.POST.get(slot.abbreviation, None)
        if toUpdate is not None:
            slot.op = True
            count = + 1
            messages.success(request, "Slot {} is operational now!".format(slot))
        slot.save()
    if count == 0:
        s = Slot.objects.filter(abbreviation=DEFAULT_SHIFT_SLOT).first()
        s.op = True
        s.save()
        messages.success(request, "There must be at leasst one slot set to operational, setting default {} ".format(s))
    return HttpResponseRedirect(reverse("shifter:dates"))


@require_safe
def todays(request):
    dayToGo = request.GET.get('date', None)
    slotToGo = request.GET.get('slot', None)
    hourToGo = request.GET.get('hour', None)
    fullUpdate = request.GET.get('fullUpdate', None) is not None
    activeShift = prepare_active_crew(dayToGo=dayToGo,
                                      slotToGo=slotToGo,
                                      hourToGo=hourToGo,
                                      fullUpdate=fullUpdate)
    todayAM=datetime.datetime.today().replace(hour=0, minute=0, second=1, microsecond=0)
    todayPM = datetime.datetime.today().replace(hour=23, minute=59, second=00, microsecond=0)
    scheduled_studies = StudyRequest.objects.filter(state__in=["B","D"],slot_start__gte=todayAM,slot_end__lte=todayPM).order_by('slot_start', 'priority')
    context = {'today': activeShift['today'],
               'checkTime': activeShift['today'].time(),
               'activeSlot': activeShift['activeSlot'],
               'activeSlots': activeShift['activeSlots'],
               'currentTeam': activeShift['currentTeam'],
               'shiftID': activeShift['shiftID'],
               'activeStudies': scheduled_studies}
    return render(request, 'today.html', prepare_default_context(request, context))


@require_safe
@login_required
def user(request):
    member = request.user
    ss = Shift.objects.filter(revision=Revision.objects.filter(valid=True).order_by('-number').first()).filter(member=member)
    dailyViolations = find_daily_rest_time_violation(scheduled_shifts=ss)
    weeklyViolations = find_weekly_rest_time_violation(scheduled_shifts=ss)
    contex = prepare_user_context(member)
    contex['dailyViolations'] = dailyViolations
    contex['weeklyViolations'] = weeklyViolations
    return render(request, 'user.html', prepare_default_context(request, contex))


@require_safe
def user_simple(request):
    if request.GET.get('id', None) is not None:
        member = Member.objects.filter(id=request.GET.get('id')).first()
        ss = Shift.objects.filter(revision=Revision.objects.filter(valid=True).order_by('-number').first()).filter(
            member=member)
        dailyViolations = find_daily_rest_time_violation(scheduled_shifts=ss)
        contex = prepare_user_context(member)
        contex['dailyViolations'] = dailyViolations
        return render(request, 'user.html', prepare_default_context(request, contex))
    messages.info(request, 'Unauthorized access. Returning back to the main page!')
    return HttpResponseRedirect(reverse("shifter:index"))


@require_safe
@login_required
def team(request):
    member = request.user
    context = {'browsable': True}
    return render(request, 'team.html',
                  prepare_default_context(request,
                                          prepare_team_context(request,
                                                               member=member,
                                                               team=None,
                                                               extraContext=context)))


@require_safe
def team_simple(request):
    if request.GET.get('mid', None) is not None:
        member = Member.objects.filter(id=request.GET.get('mid')).first()
        context = {'browsable': False}
        return render(request, 'team.html',
                      prepare_default_context(request,
                                              prepare_team_context(request,
                                                                   member=member,
                                                                   team=None,
                                                                   extraContext=context)))
    if request.GET.get('id', None) is not None:
        team = Team.objects.filter(id=request.GET.get('id')).first()
        extra_context = {'browsable': False}
        return render(request, 'team.html',
                      prepare_default_context(request,
                                              prepare_team_context(request,
                                                                   member=None,
                                                                   team=team,
                                                                   extraContext=extra_context)))

    messages.info(request, 'Unauthorized access. Returning back to the main page!')
    return HttpResponseRedirect(reverse("shifter:index"))


@require_safe
def icalendar(request):
    member = None
    team = None
    if request.GET.get('mid'):
        member = Member.objects.filter(id=request.GET.get('mid')).first()
    if request.GET.get('tid'):
        team = Team.objects.filter(id=request.GET.get('tid')).first()

    revision = Revision.objects.filter(valid=True).order_by("-number").first()

    shifts = Shift.objects.filter(member=member, revision=revision)
    studies = StudyRequest.objects.filter(member=member,state__in=["B","D"])
    if team is not None:
        shifts = Shift.objects.filter(member__team=team, revision=revision)
        studies = StudyRequest.objects.filter(member__team=team,state__in=["B","D"])
    if team is None and member is None:
        shifts = Shift.objects.filter(revision=revision)
        studies = None

    context = {
        'campaign': 'Exported Shifts',
        'shifts': shifts,
        'studies': studies,
        'member': member,
        'team': team if not None else member.team,
    }

    body = render_to_string('icalendar.ics', context)

shifts/views/errors.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, "404.html", {})


def error_500(request):
    return render(request, '500.html', {})

shifts/templates/assets.html
{% extends 'template_main.html'%}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'datatables.net-bs5/css/dataTables.bootstrap5.min.css'%}">
<link rel="stylesheet" href="{% static 'datatables.net-searchpanes-bs5/css/searchPanes.bootstrap5.min.css'%}">
{% endblock %}


{% block body %}
<div class="container-fluid mb-5 pb-5">
    <div class="row justify-content-center">
        <div class="col">
            <h2 class="text-center mb-3">Asset booking portal</h2>
            <div class="accordion" id="assets_accordion">
                <!-- New booking accordion, require user logged -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="new_booking_header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordion_booking_new" aria-expanded="false" aria-controls="accordion_booking_new">
                            New Booking
                        </button>
                    </h2>
                    <div id="accordion_booking_new" class="accordion-collapse collapse" aria-labelledby="new_booking_header" data-bs-parent="#assets_accordion">
                        <div class="accordion-body">
                            <form action="{% url "shifter:assets" %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{form | crispy}}
                                <br>
                                <input class="btn btn-success" type="submit" value="Submit">
                            </form>
                        </div>
                    </div>
                </div>
                <!-- Booking list, opened by default -->
                <div class="accordion-item">
                    <h2 class="accordion-header" id="booking_header">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#accordion_booking" aria-expanded="true" aria-controls="accordion_booking">
                            Last Bookings
                        </button>
                    </h2>
                    <div id="accordion_booking" class="accordion-collapse collapse show" aria-labelledby="booking_header" data-bs-parent="#assets_accordion">
                        <div class="accordion-body">
                            <table id="table_id" class="table table-striped" data-content_url="{% url 'ajax.get_assets'  %}">
                                <thead>
                                    <tr>
                                        <th scope="col">Member</th>
                                        <th scole="col">Status</th>
                                        <th scope="col">Asset</th>
                                        <th scope="col">Use start</th>
                                        <th scope="col">Use end</th>
                                        <th scope="col">Initial comments</th>
                                        <th scope="col">Closing comments</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <!-- filled by AJAX -->
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Closing booking modal -->
<div class="modal" id="closing_booking_modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="asset_title"></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
            <form id="close_booking_form" action="{% url "shifter:assets-close" %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{closing_form | crispy}}
            </form>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success" form="close_booking_form">Close Booking</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}


{%  block js %}
    <script type="text/javascript" src="{% static 'datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net-select/js/dataTables.select.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net-searchpanes/js/dataTables.searchPanes.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'datatables.net-searchpanes-bs5/js/searchPanes.bootstrap5.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/assets.min.js' %}"></script>
{% endblock %}

shifts/templates/calendar.html
<div class='container'>
      <div id='calendar' style="padding-top: 10px;"
           data-source-shifts="{{event_source}}"
           data-source-studies="{%  url 'studies:ajax.get_studies' %}"
           data-source-holidays="{%  url 'ajax.get_holidays' %}"
           data-source-team-events="{%  url 'ajax.get_team_events' %}"
           data-default-date="{{defaultDate}}"></div>
</div>

<div id="calendarModal" class="modal fade">
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 id="modalTitle" class="modal-title"></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        {%if request.user.is_staff %}
        <div  class="modal-body">
            <p id="modalPre"></p>
            <p id="modalPost"></p>
        </div>
        {%endif%}
        <div class="modal-footer">
            {%if request.user.is_staff %} <a id="eventEdit" type="button" class="btn btn-danger" data-dismiss="modal">Edit pre/post messages</a> {%endif%}
            <a id="eventUrl" type="button" class="btn btn-success" data-dismiss="modal">Continue to shifter's schedule</a>
        </div>
    </div>
</div>
</div>

shifts/templates/dates.html
{% extends 'template_main.html'%}
{% block body %}
<div class="container mb-5 pb-5">
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Defined campaigns and their dates</h1>
            {% for c in campaigns %}
              <p> <span class="badge bg-primary">{{c.name}}</span> for <strong>{{c.date_start}}</strong> - <strong>{{c.date_end}}</strong> <small>(revision {{c.revision}})</small> </p>
            {% endfor%}
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col">
            <h1 class="text-center">Defined day slots</h1>
            <form action="{% url "shifter:slots-update-post" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                {% for c in slots %}
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="{{c.abbreviation}}" name="{{c.abbreviation}}" {% if c.op%}checked{%endif%} {%if not request.user.is_staff %} disabled {%endif%}>
                    <label class="form-check-label" for="flexSwitchCheckDefault"><span class="badge bg-{%if c == DEFAULT_SHIFT_SLOT%}primary{%else%}info{%endif%}">{{c.name}} ({{c.abbreviation}})</span> for <strong>{{c.hour_start}}</strong> - <strong>{{c.hour_end}}</strong></label>
                </div>
                {% endfor%}
           {%if request.user.is_staff %}  <button class="btn btn-info"  >Update Slots OP </button><h4><span class="badge bg-primary"> DefaultShiftSlot </span></h4>{%endif%}
            </form>
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Teams</h1>
            {% for c in teams %}
                <p> <a href="{%  url 'team_view' team_id=c.id %}"> {{c.name}} </a></p>
            {% endfor%}
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Shift roles</h1>
            {% for c in shiftroles %}
                <p>{{c.name}} <span class="badge bg-secondary">{{c.abbreviation}}</span> </p>
            {% endfor%}
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Member roles</h1>
            {% for c in memberroles %}
              <p>{{c.name}}  <span class="badge bg-secondary">{{c.abbreviation}}</span> </p>
            {% endfor%}
        </div>
    </div>
    <hr>
    <div class="row justify-content-center">
        <div class="col text-center">
            <h1>Available Assets</h1>
            {% for a in assets %}
              <p><span class="badge bg-secondary">{{a.asset_type}}</span> {{a.name}}</p>
            {% endfor%}
        </div>
    </div>
</div>
{% endblock %}

shifts/templates/logbook.html
{% extends 'template_main.html'%}
{% block 'body' %}
    <div class="col-sm-8 mx-auto">
      <main role="main">
        <h1> <span class="badge badge-primary"> Logbook preview </span></h1>
         {%for shid in lastShiftIds%}<a class="btn btn{%if shid == shiftID %}{%else%}-outline{%endif%}-primary" href="?shiftID={{shid}}">{{shid}}</a> {%endfor%}
      </main>
    </div>
    {% include 'shift_log.html'  %}
{% endblock %}

shifts/templates/shiftexchange_email.html
Dear {{approve}},

This is an automatic message regarding a Shift Exchange(#{{sExId}}) with you.
The initial request comes from {{requestor}}

--
The initial check does not show any problem with the following shifts that are proposed to be exchanged:

{%for one in shifts%}
{{one}}
{%endfor%}
--

NOTE: This is not a change confirmation but a request for now.

Please visit your shifter space ({{ domain }}/user?swaps), and approve or reject the proposal.

Note: Manage your notifications in {{ domain }}/user?notifications
Thanks!
--
CR_OperationsGroup@ess.eu

shifts/templates/shifts_upload.html
{% extends 'template_main.html'%}
{% block body %}

<div class="container mb-5 pb-5">
    <div class="row justify-content-center">
        <div class="col">
            <h5>How to prepare an input</h5>
            <p>Provide a file (in the CSV format) following the instructions in gitlab.</p>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col">
            <h1>Provide an input</h1>
            <form action="{% url 'shifter:shift-upload-post' %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="csv_file" class="form-label">CSV File: </label>
                    <input class="form-control-file" type="file" name="csv_file" id="csv_file" required>
                </div>
                <div class="mb-3">
                    <label for="camp" class="form-label">Campaign: </label>
                    <select class="form-select" name='camp' id='camp' required>
                        <option value="">Campaign assignment</option>
                        {% for camp in campaigns %}
                            <option value="{{camp.id}}">{{camp.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="revision" class="form-label">Revision: </label>
                    <select class="form-select" name='revision' id='revision' onchange="return newRevBlock(this.value)">
                        <option value="-1"> --> create new <--- </option>
                        {% for rev in revisions %}
                            <option value="{{rev.number}}"
                                    {% if rev == latest_revision %}selected="selected"{%endif%}>
                                {{rev}} (validity: {{rev.valid}}) </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3" id="new-revision-block">
                    <label for="new-revision-name">New revision name</label>
                    <input class="form-control" name="new-revision-name" id="new-revision-name" aria-describedby="new-revision-name-help" placeholder="some default for revision">
                    <small id="new-revision-name-help" class="form-text text-muted">Give some short distinct name, like 'New W20-28'.</small><br>
                </div>
                <div class="mb-3">
                    <label for="role" class="form-label">Role: </label>
                    <select class="form-select" name='role' id='role'>
                        <option value="-1">Role assignment (don't change if use default)</option>
                        {% for r in roles %}
                            <option value="{{r.id}}">{{r.name}} </option>
                        {% endfor %}
                    </select>
                </div>
            <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{%  block js %}
<script type="text/javascript">
    function newRevBlock(rev){
      if (rev>0){$("#new-revision-block").hide();}
      else{$("#new-revision-block").show();}
      return false;
    }
     $(document).ready(function() {
        newRevBlock(99)
    });
</script>
{% endblock %}

shifts/templates/shiftsnewrevision_email.html
Dear Shifter,

This is an automatic message regarding the new revision available for a preview.
As your name is part of the new import, please go to the shifter web and consult details on your new shifts:

--
The new revision {{revision}}
--

Note: Manage your notifications in {{ domain }}/user?notifications
Thanks!
--
CR_OperationsGroup@ess.eu